dist: xenial

os:
    - linux

language: node_js

node_js:
    - 10

install:
    - npm install
    - npm install -g ganache-cli

before_script:
    - npm run lint
    - npm run compile
    - npm run ganache > /dev/null 2>&1 &

script:
    - npm test
    - npm run coverage
    - cat coverage/lcov.info | coveralls
