dist: xenial

os:
    - linux

language: node_js

node_js:
    - node

install:
    - npm install
    - npm install -g ganache-cli

before_script:
    - npm run ganache &

script:
    - npm run lint
    - npm test
