dist: xenial

os:
    - linux

language: node_js

node_js:
    - 10

install:
    - npm install
    - npm install -g ganache-cli

before_script:
    - npm run lint
    - npm run compile
    - npm run ganache &

script:
    - npm test
