dist: xenial

language: node_js

node_js:
    - node

install:
    - npm install

before_script:
    - npm run ganache &

script:
    - npm run lint
    - npm test
    - cat coverage/lcov.info | coveralls
